name: Tetration-Calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: cargo fetch

    - name: Build in Release Mode
      run: cargo build --release

    - name: Run the Program
      run: |
        ./home/runner/work/Tetration-Calculator/Tetration-Calculator <<EOF
        Enter
        2
        5
        EOF

    - name: Wait or Forcefully Kill
      run: |
        sleep 60
