name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: cargo fetch

    - name: Build in Release Mode
      run: cargo build --release

    - name: Run the Program
      run: |
        # Find the binary executable produced by your Rust program
        executable=$(find . -name "tetration-calculator" -type f)

        if [ -z "$executable" ]; then
          echo "Executable not found. Check your program name."
          exit 1
        fi

        # Run the program using the 'expect' command to provide input from input.txt
        expect -c "
        spawn $executable
        expect \"Enter\r\"
        send \"Enter\n\"
        expect \"2\r\"
        send \"2\n\"
        expect \"5\r\"
        send \"5\n\"
        expect \"Enter\r\"
        send \"Enter\n\"
        expect \"7\r\"
        send \"7\n\"
        expect \"3\r\"
        send \"3\n\"
        expect \"Enter\r\"
        send \"Enter\n\"
        interact
        "

    - name: Wait or Forcefully Kill
      run: |
        sleep 60
        pkill -f tetration-calculator
