name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: cargo fetch

    - name: Build in Release Mode
      run: cargo build --release

    - name: Run the Program
      run: |
        # Find the binary executable produced by your Rust program
        executable=$(find . -name "tetration-calculator" -type f)

        if [ -z "$executable" ]; then
          echo "Executable not found. Check your program name."
          exit 1
        fi

        while read -r line; do
          echo "$line"
          echo "$line" | $executable
        done < .github/workflows/workflow_commands.txt

    - name: Wait or Forcefully Kill
      run: |
        sleep 60
        pkill -f tetration-calculator
