name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-run-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: cargo fetch
      - name: Clean the Cargo
        run: cargo clean
      - name: Re-build in Release Mode
        run: cargo build --release
      - name: Run the Program on Linux
        run: |
          executable=$(find . -name "tetration-calculator" -type f)
          if [ -z "$executable" ]; then
            echo "Executable not found. Check your program name."
            exit 1
          fi
          $executable --base 2 --height 5
          sleep 5
          $executable --base 7 --height 3
      - name: Wait and Kill the Process
        run: |
          sleep 10
          if pgrep -f tetration-calculator; then
            pkill -f tetration-calculator

  build-and-run-freebsd:
    runs-on: freebsd-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: cargo fetch
      - name: Clean the Cargo
        run: cargo clean
      - name: Re-build in Release Mode
        run: cargo build --release
      - name: Run the Program on FreeBSD
        run: |
          executable=$(find . -name "tetration-calculator" -type f)
          if [ -z "$executable" ]; then
            echo "Executable not found. Check your program name."
            exit 1
          fi
          $executable --base 2 --height 5
          sleep 5
          $executable --base 7 --height 3
      - name: Wait and Kill the Process
        run: |
          sleep 10
          if pgrep -f tetration-calculator; then
            pkill -f tetration-calculator

  build-and-run-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: cargo fetch
      - name: Clean the Cargo
        run: cargo clean
      - name: Re-build in Release Mode
        run: cargo build --release
      - name: Run the Program on Windows
        run: |
          $executable = Get-Item -Path "$(Get-Location)/*.exe"
          if ($executable -eq $null) {
            Write-Host "Executable not found. Check your program name."
            exit 1
          }
          & $executable --base 2 --height 5
          Start-Sleep -Seconds 5
          & $executable --base 7 --height 3
      - name: Wait and Kill the Process
        run: |
          Start-Sleep -Seconds 10
          $process = Get-Process -Name "tetration-calculator" -ErrorAction SilentlyContinue
          if ($process -ne $null) {
            Stop-Process -Name "tetration-calculator" -Force
          }
