name: Tetration-Calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: cargo fetch

    - name: Build in Release Mode
      run: cargo build --release --verbose

    - name: Run Program in the Background
      run: |
        ./target/release/Tetration-Calculator &
        sleep 60
        
    - name: Kill Program
      run: pkill -f 'Tetration-Calculator'  # Replace 'your_program' with the actual program name

    - name: Run tests
      run: cargo test --verbose
