name: Teration Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: cargo fetch  # This will download and install the project's dependencies
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
